### ISSUE TITLE
question about charades dataset

### ISSUE THREAD

**Issue by onlyonewater** [JonghwanMun/LGI4temporalgrounding#10]
Hi @JonghwanMun , thank you so much for releasing the code, but I have a question, why it performs well on charades dataset? Did you use a raw features on charades or a fine-tuning features on charades? Thanks!!!

**Comment by JonghwanMun** [comment]
I used the I3D network pre-trained on Charades as ExCL[1] and PfTML-GA[2] did.
Following the github https://github.com/piergiaj/pytorch-i3d, you can extract visual features for Charades-STA dataset.
As I remember, "model/rgb_charades.pt" in the github corresponds to the I3D network pre-trained on Charades dataset.

[1] SohamGhosh,AnuvaAgarwal,ZaranaParekh,andAlexan- der Hauptmann. ExCL: Extractive Clip Localization Using Natural Language Descriptions. arXiv preprint arXiv:1904.02755, 2019.
[2] Cristian Rodriguez Opazo, Edison Marrese-Taylor, Fate- meh Sadat Saleh, Hongdong Li, and Stephen Gould. Proposal-free Temporal Moment Localization of a Natural- Language Query in Video using Guided Attention. arXiv preprint arXiv:1908.07236, 2019.

**Comment by onlyonewater** [comment]
OK, I get it! Thanks!!

**Comment by xljh0520** [comment]
> I used the I3D network fine-tuned on Charades as ExCL[1] and PfTML-GA[2] did. Following the github https://github.com/piergiaj/pytorch-i3d, you can extract visual features for Charades-STA dataset. As I remember, "model/rgb_charades.pt" in the github corresponds to the I3D network pre-trained on Charades dataset.
> 
> [1] SohamGhosh,AnuvaAgarwal,ZaranaParekh,andAlexan- der Hauptmann. ExCL: Extractive Clip Localization Using Natural Language Descriptions. arXiv preprint arXiv:1904.02755, 2019. [2] Cristian Rodriguez Opazo, Edison Marrese-Taylor, Fate- meh Sadat Saleh, Hongdong Li, and Stephen Gould. Proposal-free Temporal Moment Localization of a Natural- Language Query in Video using Guided Attention. arXiv preprint arXiv:1908.07236, 2019.

Hi, thanks for your answer! I have a question about how you fine-tune the I3D network on Charades. Could you share more detail?
