### ISSUE TITLE
loading charades dataset is too slow

### ISSUE THREAD

**Issue by onlyonewater** [JonghwanMun/LGI4temporalgrounding#12]
when I run the code, I found that loading the charades dataset is too slow, do you have any solutions??

**Comment by onlyonewater** [comment]
and the download link has some problem, I can't download the pretrained model

**Comment by JonghwanMun** [comment]
Sorry for the late response.
I fix the link and now download speed is fast!

Use following command :)
```
wget http://cvlab.postech.ac.kr/research/LGI/LGI_data.tar.gz
wget http://cvlab.postech.ac.kr/research/LGI/charades_data.tar.gz
wget https://cvlab.postech.ac.kr/research/LGI/LGI_pretrained_models.tar.gz
```

**Comment by onlyonewater** [comment]
thanks!!!

**Comment by QichenZheng** [comment]
> Sorry for the late response.
> I fix the link and now download speed is fast!
> 
> Use following command :)
> 
> ```
> wget http://cvlab.postech.ac.kr/research/LGI/LGI_data.tar.gz
> wget http://cvlab.postech.ac.kr/research/LGI/charades_data.tar.gz
> wget https://cvlab.postech.ac.kr/research/LGI/LGI_pretrained_models.tar.gz
> ```

The download link for LGI_data.tar.gz is unavailable now.Can u update it again?Thank you!
