### ISSUE TITLE
where is the config.yml???

### ISSUE THREAD

**Issue by onlyonewater** [JonghwanMun/LGI4temporalgrounding#13]
hi, when i finished training the model, and now I want to eval the model. i got the checkpoint `best.pkl` file(from the dir `results/charades/tgn_lgi/LGI/checkpoints`), but where the config.yml file? i can't find it.

**Comment by JonghwanMun** [comment]
According to following: https://github.com/JonghwanMun/LGI4temporalgrounding/blob/64ef8df6454d8d48d0e75f1217fdda653ad2ef26/src/model/abstract_network.py#L34-L36
The configuration should be saved in `results/charades/tgn_lgi/LGI/` if verbose is True.


However, currently, default `verbose` is set by False.
Please revise following line `super(LGI, self).__init__(config=config, logger=logger, verbose=True)`
https://github.com/JonghwanMun/LGI4temporalgrounding/blob/64ef8df6454d8d48d0e75f1217fdda653ad2ef26/src/model/LGI.py#L12


Sorry for the Inconvenience.

**Comment by onlyonewater** [comment]
ok, i got it, thanks
