### ISSUE TITLE
use wget to download LGI_data.tar.gz from  http://cvlab.postech.ac.kr/research/LGI/LGI_data.tar.gz always fails in 26% 8.60G

### ISSUE THREAD

**Issue by QichenZheng** [JonghwanMun/LGI4temporalgrounding#14]
![image](https://user-images.githubusercontent.com/53223368/124302629-09bdab80-db94-11eb-8724-bf3a6c7c693b.png)
I've tried many times to download the LGI_data.tar.gz,and it all fails in the same place.Is the link for wget still available?Can u check the link? Thank you!

**Comment by QichenZheng** [comment]
I am using the new link that you updated 6 days ago: http://cvlab.postech.ac.kr/research/LGI/charades_data.tar.gz, but it seems to be having some problems at the moment.The download will be stuck at 26%

**Comment by JonghwanMun** [comment]
Sorry for the late response.
I checked that, for me, the following two links are working (the download is done using ). 

![image](https://user-images.githubusercontent.com/6416693/124405089-90cb7900-dd78-11eb-9935-5510eab14775.png)
![image](https://user-images.githubusercontent.com/6416693/124405153-cbcdac80-dd78-11eb-925b-b15d19fcc5fa.png)


However, as you mentioned, the following link (to download `LGI_dta.tar.gz`) is broken.
I'll check it. Sorry for the inconvenience.
![image](https://user-images.githubusercontent.com/6416693/124405789-7b574e80-dd7a-11eb-8ffd-94e02a0f47ec.png)

**Comment by JonghwanMun** [comment]
Currently, the link is broken.
So, alternatively, download preprocessed annotation files using `wget http://cvlab.postech.ac.kr/~jonghwan/data/LGI/anet_ann_data.tar.gz` and download the c3d feature from http://activity-net.org/challenges/2016/download.html.

Briefly,
```
### Download data for activitynet dataset
wget http://cvlab.postech.ac.kr/~jonghwan/data/LGI/anet_ann_data.tar.gz # annotation + (preprocessed ones)
mv LGI data
rm anet_ann_data.tar.gz
# please download the C3D features from http://activity-net.org/challenges/2016/download.html
# move the C3D feature file into data/LGI/feats/
```


-------------------Revised
Now fixed, so downloading `LGI_dta.tar.gz` is also working :)

**Comment by QichenZheng** [comment]
Yeah,thanks for your help!
