### ISSUE TITLE
Missing Charades Features

### ISSUE THREAD

**Issue by XinliYu** [JonghwanMun/LGI4temporalgrounding#5]
The file at http://cvlab.postech.ac.kr/~jonghwan/data/LGI/LGI_data.tar.gz seems only has ActivityNet features. We are interested in this model because it is reported to perform well on the Charades dataset. Could you help provide access to the features used for experimenting the Charades dataset? Many thanks!

**Comment by JonghwanMun** [comment]
Sorry for the late response.
I will make the feature be available by the link [http://cvlab.postech.ac.kr/~jonghwan/data/LGI/charades_data.tar.gz](http://cvlab.postech.ac.kr/~jonghwan/data/LGI/charades_data.tar.gz).
