### ISSUE TITLE
About function get_fixed_length_feat() in abstract_dataset.py

### ISSUE THREAD

**Issue by SCZwangxiao** [JonghwanMun/LGI4temporalgrounding#7]
```python
def get_fixed_length_feat(self, feat, num_segment, start_pos, end_pos):
    nfeats = feat[:,:].shape[0]
    if nfeats <= self.S:
        stride = 1
    else:
        stride = nfeats * 1.0 / num_segment
    if self.split != "train":
        spos = 0
    else:
        random_end = -0.5 + stride
        if random_end == np.floor(random_end):
            random_end = random_end - 1.0
        spos = np.random.random_integers(0,random_end)
    s = np.round( np.arange(spos, nfeats-0.5, stride) ).astype(int)
    start_pos =  float(nfeats-1.0) * start_pos
    end_pos = float(nfeats-1.0) * end_pos
````
I 'm confused about the sampling procedure:
- Why should we introduce a random function when calculating spos ?
```python
spos = np.random.random_integers(0,random_end)
```

**Comment by JonghwanMun** [comment]
Let us consider the following example. 
Assume that we want to sample 100 segments from a video with 200 segments, then it can be simply achieved by sampling segments with stride 2 from `spos`.
In this case, there are two candidates for `spos`---0 or 1.
So I randomly sample the `spos` from possible ones.

**Comment by SCZwangxiao** [comment]
> 
> 
> Let us consider the following example.
> Assume that we want to sample 100 segments from a video with 200 segments, then it can be simply achieved by sampling segments with stride 2 from `spos`.
> In this case, there are two candidates for `spos`---0 or 1.
> So I randomly sample the `spos` from possible ones; this acts as augmentation.
> 
> Note that at inference time, I fix the `spos` as 0.

It's so kind of you to give such a detailed explanation!
